### ISSUE TITLE
Wrong convergence interval in QuanvolutionalNeuralNetwork

### ISSUE THREAD

**Issue by albertnieto** [XanaduAI/qml-benchmarks#12]
In QuanvolutionalNeuralNetwork model class, the convergence interval is wrong:
```
convergence_interval=10e-4
```
This will cause errors in model_utils
```
TypeError: slice indices must be integers or None or have an __index__ method
```
I guess default should be 200.

**Comment by josephbowles** [comment]
Hi Albert, thanks for pointing this out. Indeed was an artefact from when we had a 'convergence threshold' instead. Will push a change.
